import { neon } from '@neondatabase/serverless';
import { requireAccount } from './auth-helper.js';
import { chatMessageSchema } from './schemas.js';
import { parseBody } from './validate.js';
import type { VercelRequest, VercelResponse } from '@vercel/node';

interface ChatHistoryRow {
  role: string;
  content: string;
  created_at: string;
}

interface TransactionContextRow {
  type: string;
  amount: number | string;
  description: string;
  wallet_type: string;
  dateoftrans: string;
}

interface WalletContextRow {
  name: string;
  type: string;
  initial_balance: number | string;
  current_balance: number | string;
  status: string | null;
}

interface GoalContextRow {
  title: string;
  target_amount: number | string;
  current_amount: number | string;
  deadline: string | null;
  category: string | null;
  priority: number | null;
}

interface ColumnRow {
  column_name: string;
}

interface StreamDelta {
  choices?: Array<{
    delta?: {
      content?: string;
    };
  }>;
}

const sql = neon(process.env.DATABASE_URL!);
const CHAT_SCHEMA_CACHE_TTL_MS = 5 * 60 * 1000;
const FINANCE_ONLY_RESPONSE = 'I can only help with finance-related topics like budgeting, expenses, wallet balances, savings goals, investments, and economic questions.';

let chatSchemaValidatedAt = 0;
let chatSchemaValidationPromise: Promise<void> | null = null;

async function getAiChatColumns(): Promise<Set<string>> {
  const rows = await sql`
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'ai_chats'
  ` as ColumnRow[];
  return new Set(rows.map((row) => String(row.column_name).toLowerCase()));
}

async function ensureAiChatsSchema(): Promise<void> {
  await sql`
    CREATE TABLE IF NOT EXISTS ai_chats (
      chat_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
      acc_id INTEGER NOT NULL REFERENCES accounts(acc_id) ON DELETE CASCADE,
      role TEXT NOT NULL,
      content TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `;

  const columns = await getAiChatColumns();
  const tryExec = async (query: Promise<unknown>): Promise<void> => {
    try {
      await query;
    } catch {
      // Ignore incompatible legacy variants and validate below.
    }
  };

  if (!columns.has('chat_id') && columns.has('id')) {
    await tryExec(sql`ALTER TABLE ai_chats RENAME COLUMN id TO chat_id`);
  }
  if (!columns.has('acc_id') && columns.has('account_id')) {
    await tryExec(sql`ALTER TABLE ai_chats RENAME COLUMN account_id TO acc_id`);
  }
  if (!columns.has('created_at') && columns.has('createdat')) {
    await tryExec(sql`ALTER TABLE ai_chats RENAME COLUMN createdat TO created_at`);
  }

  const refreshed = await getAiChatColumns();
  if (!refreshed.has('chat_id')) {
    await tryExec(sql`ALTER TABLE ai_chats ADD COLUMN chat_id INTEGER GENERATED BY DEFAULT AS IDENTITY`);
  }
  if (!refreshed.has('acc_id')) {
    await tryExec(sql`ALTER TABLE ai_chats ADD COLUMN acc_id INTEGER REFERENCES accounts(acc_id) ON DELETE CASCADE`);
  }
  if (!refreshed.has('role')) {
    await tryExec(sql`ALTER TABLE ai_chats ADD COLUMN role TEXT`);
  }
  if (!refreshed.has('content')) {
    await tryExec(sql`ALTER TABLE ai_chats ADD COLUMN content TEXT`);
  }
  if (!refreshed.has('created_at')) {
    await tryExec(sql`ALTER TABLE ai_chats ADD COLUMN created_at TIMESTAMPTZ DEFAULT NOW()`);
  }

  await tryExec(sql`ALTER TABLE ai_chats ALTER COLUMN acc_id SET NOT NULL`);
  await tryExec(sql`ALTER TABLE ai_chats ALTER COLUMN role SET NOT NULL`);
  await tryExec(sql`ALTER TABLE ai_chats ALTER COLUMN content SET NOT NULL`);
  await tryExec(sql`ALTER TABLE ai_chats ALTER COLUMN created_at SET DEFAULT NOW()`);
  await tryExec(sql`ALTER TABLE ai_chats ADD PRIMARY KEY (chat_id)`);
  await tryExec(sql`CREATE INDEX IF NOT EXISTS idx_ai_chats_acc_id_chat_id ON ai_chats(acc_id, chat_id)`);
}

async function ensureAiChatsSchemaCached(): Promise<void> {
  const now = Date.now();
  if (now - chatSchemaValidatedAt < CHAT_SCHEMA_CACHE_TTL_MS) {
    return;
  }

  if (!chatSchemaValidationPromise) {
    chatSchemaValidationPromise = (async () => {
      await ensureAiChatsSchema();
      const columns = await getAiChatColumns();
      const required = ['chat_id', 'acc_id', 'role', 'content', 'created_at'];
      const missing = required.filter((column) => !columns.has(column));
      if (missing.length > 0) {
        throw new Error(`Unsupported ai_chats schema. Missing: ${missing.join(', ')}`);
      }
      chatSchemaValidatedAt = Date.now();
    })();
  }

  try {
    await chatSchemaValidationPromise;
  } finally {
    chatSchemaValidationPromise = null;
  }
}

function normalizePrompt(message: string): string {
  return message.toLowerCase().replace(/[^a-z0-9\s]/g, ' ');
}

function shouldRefusePrompt(message: string): boolean {
  const normalized = normalizePrompt(message);

  const financePattern = /\b(finance|financial|budget|budgeting|money|expense|expenses|income|spending|spend|transaction|transactions|wallet|wallets|balance|balances|saving|savings|goal|goals|invest|investment|investments|stock|stocks|crypto|debt|loan|loans|cash\s?flow|net\s?worth|economy|economic|economics|retirement|emergency\s?fund|summary|summarize|monthly\s+summary)\b/;
  if (financePattern.test(normalized)) {
    return false;
  }

  const clearlyOffTopicPattern = /\b(weather|temperature|forecast|sports|game|score|movie|movies|song|songs|music|lyrics|poem|poetry|joke|funny|recipe|cook|cooking|travel|flight|hotel|translate|translation|code|programming|javascript|typescript|python|bug|debug|homework|essay|history|biology|chemistry|physics)\b/;
  return clearlyOffTopicPattern.test(normalized);
}

function writeSseHeaders(res: VercelResponse): void {
  res.writeHead(200, {
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
  });
}

function writeSseMessage(res: VercelResponse, content: string): void {
  const payload = {
    choices: [
      {
        delta: {
          content,
        },
      },
    ],
  };

  res.write(`data: ${JSON.stringify(payload)}\n\n`);
  res.write('data: [DONE]\n\n');
  res.end();
}

async function storeChatMessage(accId: number, role: 'user' | 'assistant', content: string): Promise<void> {
  await sql`
    INSERT INTO ai_chats (acc_id, role, content)
    VALUES (${accId}, ${role}, ${content})
  `;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const { method } = req;

  const account = await requireAccount(req, res);
  if (!account) return;
  const accId = account.acc_id;

  try {
    await ensureAiChatsSchemaCached();

    if (method === 'GET') {
      const history = await sql`
        SELECT role, content, created_at
        FROM ai_chats
        WHERE acc_id = ${accId}
        ORDER BY chat_id ASC
      ` as ChatHistoryRow[];
      return res.status(200).json({ success: true, data: history });
    }

    if (method === 'DELETE') {
      await sql`DELETE FROM ai_chats WHERE acc_id = ${accId}`;
      return res.status(200).json({ success: true, message: 'Chat cleared' });
    }

    if (method !== 'POST') {
      res.setHeader('Allow', ['GET', 'POST', 'DELETE']);
      return res.status(405).json({ error: 'Method not allowed' });
    }

    const payload = parseBody(chatMessageSchema, req.body, res);
    if (!payload) return;

    const { message } = payload;
    await storeChatMessage(accId, 'user', message);

    if (shouldRefusePrompt(message)) {
      await storeChatMessage(accId, 'assistant', FINANCE_ONLY_RESPONSE);
      writeSseHeaders(res);
      writeSseMessage(res, FINANCE_ONLY_RESPONSE);
      return;
    }

    let transactionsText = 'No recent transactions found.';
    try {
      const transactions = await sql`
        SELECT type, amount, description, wallet_type, dateoftrans
        FROM transactions
        WHERE account_id = ${accId}
        ORDER BY dateoftrans DESC
        LIMIT 30
      ` as TransactionContextRow[];

      if (transactions.length > 0) {
        transactionsText = JSON.stringify(
          transactions.map((transaction) => ({
            date: transaction.dateoftrans,
            type: transaction.type,
            amount: transaction.amount,
            desc: transaction.description,
            wallet: transaction.wallet_type,
          })),
        );
      }
    } catch (error: unknown) {
      console.error('Chat API: error fetching transactions:', error instanceof Error ? error.message : String(error));
    }

    let walletsText = 'No wallets found.';
    try {
      const wallets = await sql`
        SELECT
          w.name,
          w.type,
          w.initial_balance,
          w.status,
          (
            w.initial_balance +
            COALESCE(SUM(CASE
              WHEN t.type = 'Income' AND t.wallet_id = w.wallet_id THEN t.amount
              WHEN t.type = 'Transfer' AND t.transfer_to_wallet_id = w.wallet_id THEN t.amount
              WHEN t.type = 'Transfer'
                AND t.transfer_to_wallet_id IS NULL
                AND t.wallet_id = w.wallet_id
                AND (t.description ILIKE 'Transfer from%' OR t.description ILIKE 'Transfer In from%')
              THEN t.amount
              ELSE 0 END), 0) -
            COALESCE(SUM(CASE
              WHEN t.type = 'Expense' AND t.wallet_id = w.wallet_id THEN t.amount
              WHEN t.type = 'Transfer' AND t.transfer_from_wallet_id = w.wallet_id THEN t.amount
              WHEN t.type = 'Transfer'
                AND t.transfer_from_wallet_id IS NULL
                AND t.wallet_id = w.wallet_id
                AND (t.description ILIKE 'Transfer to%' OR t.description ILIKE 'Transfer Out to%')
              THEN t.amount
              ELSE 0 END), 0)
          ) AS current_balance
        FROM wallets w
        LEFT JOIN transactions t
          ON t.account_id = w.account_id
        WHERE w.account_id = ${accId}
        GROUP BY w.wallet_id
        ORDER BY w.created_at ASC
      ` as WalletContextRow[];

      if (wallets.length > 0) {
        walletsText = JSON.stringify(
          wallets.map((wallet) => ({
            name: wallet.name,
            type: wallet.type,
            initial_balance: wallet.initial_balance,
            current_balance: wallet.current_balance,
            status: wallet.status,
          })),
        );
      }
    } catch (error: unknown) {
      console.error('Chat API: error fetching wallets:', error instanceof Error ? error.message : String(error));
    }

    let goalsText = 'No savings goals found.';
    try {
      const goals = await sql`
        SELECT title, target_amount, current_amount, deadline, category, priority
        FROM goals
        WHERE account_id = ${accId}
        ORDER BY created_at DESC
      ` as GoalContextRow[];

      if (goals.length > 0) {
        goalsText = JSON.stringify(
          goals.map((goal) => ({
            title: goal.title,
            target: goal.target_amount,
            saved: goal.current_amount,
            progress:
              Number(goal.target_amount) > 0
                ? `${((Number(goal.current_amount) / Number(goal.target_amount)) * 100).toFixed(1)}%`
                : '0%',
            deadline: goal.deadline,
            category: goal.category,
            priority: goal.priority,
          })),
        );
      }
    } catch (error: unknown) {
      console.error('Chat API: error fetching goals:', error instanceof Error ? error.message : String(error));
    }

    const systemPrompt = {
      role: 'system' as const,
      content: `You are Kwarta AI, a strict financial assistant bot. You must ONLY answer questions related to finance, budgeting, money management, investments, economics, or the user's transaction data. If the user asks about anything else, politely decline and steer the conversation back to finance. Be helpful, concise, and friendly. You MUST use Markdown for formatting (lists, bolding, etc.).

Here is the user's REAL-TIME wallet data (this is the AUTHORITATIVE source for balances):
${walletsText}

IMPORTANT: Each wallet has an "initial_balance" (the starting amount when created) and a "current_balance" (initial + all income/transfers in - all expenses/transfers out). When the user asks "what is my balance for X wallet?", ALWAYS use the "current_balance" field from the wallet data above. Do NOT try to manually calculate it from transactions; the current_balance already includes the initial balance and all transactions.

Here is the user's REAL-TIME transaction data (recent activity):
${transactionsText}

CRITICAL DATA OVERRIDE:
Users frequently edit, delete, or wipe their transactions. ALWAYS base your calculations strictly on the JSON data provided above.
If the data above says "No recent transactions found.", it means the user has DELETED everything. You MUST proudly state that they have ZERO transactions and ZERO expenses/income. You are FORBIDDEN from quoting, repeating, or remembering any numbers, totals, or data from previous chat history messages. The chat history is a lie if it conflicts with the JSON data above.

IMPORTANT INSTRUCTION FOR UI VISUALS:
If the user explicitly asks for a visual summary, graph, chart, or visual breakdown:
- If they ask about Income, output exactly "[CHART:INCOME]" at the very end of your response.
- If they ask about Expenses, output exactly "[CHART:EXPENSE]" at the very end of your response.
- If they ask for a general summary without specifying, default to outputting "[CHART:EXPENSE]".

Here is the user's SAVINGS GOALS data (SECONDARY context - only use when goals are explicitly asked about):
${goalsText}

QUERY TYPE ROUTING - follow these rules strictly:
1. "Monthly Summary" or "summary" -> Focus ONLY on TRANSACTION data: total income, total expenses, net cash flow, spending categories, and wallet balances. Do NOT talk about savings goals unless the user specifically mentions them.
2. "Top Expense" or "expenses" -> Analyze TRANSACTION data to find the biggest expense categories and amounts.
3. "Recent Transactions" -> List recent transactions from the transaction data.
4. "Wallet Breakdown" -> Show wallet balances and transaction activity per wallet.
5. "Budget Advice" or "Savings Tips" -> Give general budgeting advice. You may briefly reference goals if relevant, but focus on transaction patterns.
6. "My goals" or "goals" or "savings goals" -> ONLY THEN provide a detailed goals breakdown with progress, deadlines, and savings advice.
7. Any other finance question -> Use the most relevant data source (transactions, wallets, or goals) based on context.`,
    };

    const apiKey = process.env.DEEPSEEK_API_KEY?.replace(/^"|"$/g, '') || null;
    if (!apiKey) {
      return res.status(500).json({ error: 'API key missing' });
    }

    const fetchRes = await fetch('https://api.deepseek.com/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'deepseek-chat',
        messages: [systemPrompt, { role: 'user' as const, content: message }],
        temperature: 0.7,
        stream: true,
      }),
    });

    if (!fetchRes.ok) {
      return res.status(502).json({ error: 'AI provider error' });
    }

    const streamBody = fetchRes.body;
    if (!streamBody) {
      return res.status(502).json({ error: 'AI provider error' });
    }

    writeSseHeaders(res);

    const reader = streamBody.getReader();
    const decoder = new TextDecoder('utf-8');
    let fullResponse = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      const chunkStr = decoder.decode(value, { stream: true });
      res.write(chunkStr);

      const lines = chunkStr.split('\n');
      for (const line of lines) {
        if (line.startsWith('data: ') && line !== 'data: [DONE]') {
          try {
            const parsed = JSON.parse(line.slice(6)) as StreamDelta;
            const content = parsed.choices?.[0]?.delta?.content;
            if (content) {
              fullResponse += content;
            }
          } catch {
            // Ignore malformed stream chunks.
          }
        }
      }
    }

    res.write('data: [DONE]\n\n');
    res.end();

    if (fullResponse) {
      await storeChatMessage(accId, 'assistant', fullResponse);
    }
  } catch (error: unknown) {
    console.error('Chat error:', error);
    if (!res.headersSent) {
      const message = error instanceof Error ? error.message : 'Internal server error';
      res.status(500).json({ error: message });
    }
  }
}
