import { neon } from '@neondatabase/serverless';
import { requireAccount } from './auth-helper.js';
import {
  createTransactionSchema,
  deleteTransactionSchema,
  transferFundsSchema,
  updateTransactionSchema,
} from './schemas.js';
import { parseBody } from './validate.js';
import type { VercelRequest, VercelResponse } from '@vercel/node';

interface ColumnRow {
  column_name: string;
}

interface RegClassRow {
  reg: string | null;
}

interface WalletRow {
  wallet_id: number;
  name: string;
  status: string | null;
}

interface BalanceRow {
  current_balance: string | number;
}

const sql = neon(process.env.DATABASE_URL!);
const SCHEMA_CACHE_TTL_MS = 5 * 60 * 1000;

let txSchemaValidatedAt = 0;
let txSchemaValidationPromise: Promise<void> | null = null;

const EXPECTED_TRANSACTION_COLUMNS = [
  'trans_id',
  'description',
  'type',
  'wallet_type',
  'wallet_id',
  'category',
  'transfer_from_wallet_id',
  'transfer_to_wallet_id',
  'amount',
  'account_id',
  'dateoftrans'
];

async function getTransactionColumns(): Promise<Set<string>> {
  const cols = await sql`
    SELECT column_name
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'transactions'
  ` as ColumnRow[];
  return new Set(cols.map(c => String(c.column_name).toLowerCase()));
}

async function ensureTransactionsSchema(): Promise<void> {
  const reg = await sql`SELECT to_regclass('public.transactions') AS reg` as RegClassRow[];
  const exists = Boolean(reg?.[0]?.reg);

  if (!exists) {
    await sql`
      CREATE TABLE IF NOT EXISTS transactions (
        trans_id SERIAL PRIMARY KEY,
        description TEXT NOT NULL,
        type TEXT NOT NULL,
        wallet_type TEXT NOT NULL,
        wallet_id INTEGER REFERENCES wallets(wallet_id),
        category TEXT,
        transfer_from_wallet_id INTEGER REFERENCES wallets(wallet_id),
        transfer_to_wallet_id INTEGER REFERENCES wallets(wallet_id),
        amount NUMERIC(12,2) NOT NULL,
        account_id INTEGER NOT NULL REFERENCES accounts(acc_id),
        dateoftrans TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `;
    return;
  }

  const cols = await getTransactionColumns();
  const tryExec = async (q: Promise<unknown>): Promise<boolean> => {
    try {
      await q;
      return true;
    } catch {
      return false;
    }
  };

  if (!cols.has('trans_id') && cols.has('id')) {
    await tryExec(sql`ALTER TABLE transactions RENAME COLUMN id TO trans_id`);
  }
  if (!cols.has('description') && cols.has('title')) {
    await tryExec(sql`ALTER TABLE transactions RENAME COLUMN title TO description`);
  }
  if (!cols.has('wallet_type') && cols.has('wallet')) {
    await tryExec(sql`ALTER TABLE transactions RENAME COLUMN wallet TO wallet_type`);
  }
  if (!cols.has('dateoftrans') && cols.has('date')) {
    await tryExec(sql`ALTER TABLE transactions RENAME COLUMN date TO dateoftrans`);
  }

  const cols2 = await getTransactionColumns();
  if (!cols2.has('description')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN description TEXT`);
  }
  if (!cols2.has('type')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN type TEXT`);
  }
  if (!cols2.has('wallet_type')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN wallet_type TEXT`);
  }
  if (!cols2.has('amount')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN amount NUMERIC(12,2)`);
  }
  if (!cols2.has('account_id')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN account_id INTEGER REFERENCES accounts(acc_id)`);
  }
  if (!cols2.has('dateoftrans')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN dateoftrans TIMESTAMPTZ`);
  }
  if (!cols2.has('wallet_id')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN wallet_id INTEGER REFERENCES wallets(wallet_id)`);

    await tryExec(sql`
      UPDATE transactions t
      SET wallet_id = w.wallet_id
      FROM wallets w
      WHERE t.wallet_type = w.name AND t.account_id = w.account_id AND t.wallet_id IS NULL
    `);
  }
  if (!cols2.has('category')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN category TEXT`);
  }
  if (!cols2.has('transfer_from_wallet_id')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN transfer_from_wallet_id INTEGER REFERENCES wallets(wallet_id)`);
  }
  if (!cols2.has('transfer_to_wallet_id')) {
    await tryExec(sql`ALTER TABLE transactions ADD COLUMN transfer_to_wallet_id INTEGER REFERENCES wallets(wallet_id)`);
  }

  await tryExec(sql`ALTER TABLE transactions ADD PRIMARY KEY (trans_id)`);
  await tryExec(sql`ALTER TABLE transactions ALTER COLUMN amount TYPE NUMERIC(12,2) USING amount::numeric`);
  await tryExec(sql`ALTER TABLE transactions ALTER COLUMN account_id TYPE INTEGER USING account_id::integer`);
  await tryExec(sql`ALTER TABLE transactions ALTER COLUMN dateoftrans TYPE TIMESTAMPTZ USING dateoftrans::timestamptz`);
  await tryExec(sql`ALTER TABLE transactions ALTER COLUMN trans_id ADD GENERATED BY DEFAULT AS IDENTITY`);
  await tryExec(sql`CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id)`);
  await tryExec(sql`CREATE INDEX IF NOT EXISTS idx_transactions_wallet_id ON transactions(wallet_id)`);
  await tryExec(sql`CREATE INDEX IF NOT EXISTS idx_transactions_transfer_from_wallet_id ON transactions(transfer_from_wallet_id)`);
  await tryExec(sql`CREATE INDEX IF NOT EXISTS idx_transactions_transfer_to_wallet_id ON transactions(transfer_to_wallet_id)`);
}

function normalizeType(value: unknown): string {
  const t = String(value || '').trim();
  if (!t) return '';
  const lower = t.toLowerCase();
  if (lower === 'income' || lower === 'expense' || lower === 'transfer') return lower[0].toUpperCase() + lower.slice(1);
  return t;
}

async function ensureTransactionsSchemaCached(): Promise<void> {
  const now = Date.now();
  if (now - txSchemaValidatedAt < SCHEMA_CACHE_TTL_MS) return;

  if (!txSchemaValidationPromise) {
    txSchemaValidationPromise = (async () => {
      await ensureTransactionsSchema();
      const cols = await getTransactionColumns();
      const missing = EXPECTED_TRANSACTION_COLUMNS.filter(c => !cols.has(c));
      if (missing.length > 0) {
        throw new Error(`Unsupported transactions schema. Missing: ${missing.join(', ')}`);
      }
      txSchemaValidatedAt = Date.now();
    })();
  }

  try {
    await txSchemaValidationPromise;
  } finally {
    txSchemaValidationPromise = null;
  }
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  const { method } = req;

  try {
    const account = await requireAccount(req, res);
    if (!account) return;

    await ensureTransactionsSchemaCached();

    if (method === 'GET') {
      const rows = await sql`
        SELECT trans_id, description, type, wallet_type, wallet_id, category, transfer_from_wallet_id, transfer_to_wallet_id, amount, account_id, dateoftrans
        FROM transactions
        WHERE account_id = ${account.acc_id}
        ORDER BY dateoftrans DESC
        LIMIT 50
      `;
      return res.status(200).json(rows);

    } else if (method === 'POST') {
      const action = String(req.query?.action || '').toLowerCase();

      if (action === 'transfer') {
        const body = parseBody(transferFundsSchema, req.body, res);
        if (!body) return;

        const fromWalletId = body.from_wallet_id;
        const toWalletId = body.to_wallet_id;
        const amountNum = body.amount;

        const walletRows = await sql`
          SELECT wallet_id, name, status
          FROM wallets
          WHERE account_id = ${account.acc_id}
            AND wallet_id IN (${fromWalletId}, ${toWalletId})
        ` as WalletRow[];

        if (walletRows.length !== 2) {
          return res.status(404).json({ error: 'One or both wallets not found' });
        }

        const fromWallet = walletRows.find(w => Number(w.wallet_id) === fromWalletId);
        const toWallet = walletRows.find(w => Number(w.wallet_id) === toWalletId);

        if (!fromWallet || !toWallet) {
          return res.status(404).json({ error: 'One or both wallets not found' });
        }

        const fromStatus = String(fromWallet.status || '').toUpperCase();
        const toStatus = String(toWallet.status || '').toUpperCase();
        if (fromStatus && fromStatus !== 'ACTIVE') {
          return res.status(400).json({ error: `Source wallet "${fromWallet.name}" is not ACTIVE` });
        }
        if (toStatus && toStatus !== 'ACTIVE') {
          return res.status(400).json({ error: `Destination wallet "${toWallet.name}" is not ACTIVE` });
        }

        const balanceRows = await sql`
          SELECT
            (
              w.initial_balance +
              COALESCE(SUM(CASE
                WHEN t.type = 'Income' AND t.wallet_id = w.wallet_id THEN t.amount
                WHEN t.type = 'Transfer' AND t.transfer_to_wallet_id = w.wallet_id THEN t.amount
                WHEN t.type = 'Transfer'
                  AND t.transfer_to_wallet_id IS NULL
                  AND t.wallet_id = w.wallet_id
                  AND (t.description ILIKE 'Transfer from%' OR t.description ILIKE 'Transfer In from%')
                THEN t.amount
                ELSE 0 END), 0) -
              COALESCE(SUM(CASE
                WHEN t.type = 'Expense' AND t.wallet_id = w.wallet_id THEN t.amount
                WHEN t.type = 'Transfer' AND t.transfer_from_wallet_id = w.wallet_id THEN t.amount
                WHEN t.type = 'Transfer'
                  AND t.transfer_from_wallet_id IS NULL
                  AND t.wallet_id = w.wallet_id
                  AND (t.description ILIKE 'Transfer to%' OR t.description ILIKE 'Transfer Out to%')
                THEN t.amount
                ELSE 0 END), 0)
            ) AS current_balance
          FROM wallets w
          LEFT JOIN transactions t
            ON t.account_id = w.account_id
          WHERE w.account_id = ${account.acc_id}
            AND w.wallet_id = ${fromWalletId}
          GROUP BY w.wallet_id
        ` as BalanceRow[];

        const currentBalance = Number(balanceRows?.[0]?.current_balance ?? 0);
        if (currentBalance < amountNum) {
          return res.status(400).json({
            error: `Insufficient funds in source wallet. Available: ${currentBalance.toFixed(2)}`
          });
        }

        const now = new Date();
        const transferRows = await sql`
          INSERT INTO transactions (
            description,
            type,
            wallet_type,
            wallet_id,
            category,
            transfer_from_wallet_id,
            transfer_to_wallet_id,
            amount,
            account_id,
            dateoftrans
          )
          VALUES (
            ${`Transfer ${fromWallet.name} to ${toWallet.name}`},
            'Transfer',
            ${fromWallet.name},
            ${fromWalletId},
            ${'transfer'},
            ${fromWalletId},
            ${toWalletId},
            ${amountNum},
            ${account.acc_id},
            ${now}
          )
          RETURNING trans_id, description, type, wallet_type, wallet_id, category, transfer_from_wallet_id, transfer_to_wallet_id, amount, account_id, dateoftrans
        `;

        return res.status(201).json({
          success: true,
          message: 'Transfer completed successfully',
          row: transferRows[0]
        });
      }

      const postBody = parseBody(createTransactionSchema, req.body, res);
      if (!postBody) return;

      const description = String(postBody.description ?? postBody.title ?? '').trim();
      const type = normalizeType(postBody.type);
      const walletType = String(postBody.wallet_type ?? postBody.wallet ?? '').trim();
      const walletId = postBody.wallet_id ?? null;
      const category = String(postBody.category ?? '').trim() || null;
      const amountNum = postBody.amount;

      const now = new Date();

      const inserted = await sql`
        INSERT INTO transactions (description, type, wallet_type, wallet_id, category, transfer_from_wallet_id, transfer_to_wallet_id, amount, account_id, dateoftrans)
        VALUES (${description}, ${type}, ${walletType}, ${walletId}, ${category}, NULL, NULL, ${amountNum}, ${account.acc_id}, ${now})
        RETURNING trans_id, description, type, wallet_type, wallet_id, category, transfer_from_wallet_id, transfer_to_wallet_id, amount, account_id, dateoftrans
      `;
      return res.status(201).json(inserted[0]);

    } else if (method === 'PUT') {
      const putBody = parseBody(updateTransactionSchema, req.body, res);
      if (!putBody) return;

      const id = putBody.trans_id ?? putBody.id;
      if (!id) return res.status(400).json({ error: 'Transaction ID required' });

      const patchDescription = putBody.description ?? putBody.title ?? null;
      const patchType = putBody.type ?? null;
      const patchWallet = putBody.wallet_type ?? putBody.wallet ?? null;
      const patchWalletId = putBody.wallet_id ?? null;
      const patchCategory = putBody.category ?? null;
      const patchAmount = putBody.amount ?? null;

      const updated = await sql`
        UPDATE transactions
        SET description = COALESCE(${patchDescription}, description),
            type = COALESCE(${patchType}, type),
            wallet_type = COALESCE(${patchWallet}, wallet_type),
            wallet_id = COALESCE(${patchWalletId}, wallet_id),
            category = COALESCE(${patchCategory}, category),
            amount = COALESCE(${patchAmount}, amount)
        WHERE trans_id = ${id} AND account_id = ${account.acc_id}
        RETURNING trans_id, description, type, wallet_type, wallet_id, category, transfer_from_wallet_id, transfer_to_wallet_id, amount, account_id, dateoftrans
      `;
      return res.status(200).json(updated[0] || null);

    } else if (method === 'DELETE') {
      const deleteBody = parseBody(deleteTransactionSchema, req.body, res);
      if (!deleteBody) return;

      const id = deleteBody.trans_id ?? deleteBody.id;
      if (!id) return res.status(400).json({ error: 'Transaction ID required' });

      const deleted = await sql`
        DELETE FROM transactions
        WHERE trans_id = ${id} AND account_id = ${account.acc_id}
        RETURNING trans_id, description, type, wallet_type, wallet_id, category, transfer_from_wallet_id, transfer_to_wallet_id, amount, account_id, dateoftrans
      `;
      return res.status(200).json(deleted[0] || null);

    } else {
      res.setHeader('Allow', ['GET', 'POST', 'PUT', 'DELETE']);
      res.status(405).end(`Method ${method} Not Allowed`);
    }
  } catch (err: unknown) {
    console.error('Transactions API error:', {
      method,
      message: err instanceof Error ? err.message : String(err),
      stack: err instanceof Error ? err.stack : undefined
    });
    const details = err instanceof Error ? err.message : String(err);
    res.status(500).json({ error: 'Database error', details });
  }
}


